repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        language: system
        entry: uv run ruff format
        types: [python]

      - id: ruff-lint
        name: ruff lint
        language: system
        entry: uv run ruff check --fix
        types: [python]

      - id: basedpyright
        name: basedpyright
        language: system
        entry: uv run basedpyright
        pass_filenames: false
        types: [python]
